name: Publish artifacts on tag
on:
  push:
    tags: [ 'v*.*.*' ]
permissions:
  contents: write
jobs:
  build-and-upload:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Extract version from tag
        run: echo "VER=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
          CURRENT=$(poetry version -s)
          if [ "$CURRENT" != "${VER}" ]; then
            echo "pyproject.toml version ($CURRENT) != tag (${VER}). Ensure Release PR was merged."; exit 1
          fi
      - uses: docker/setup-buildx-action@v3
      - run: |
          mkdir -p dist && sudo chown -R 4000:4000 dist
          docker compose -f tools/build/docker-compose.yml run --rm pirate-image-gen
          ls -lh dist
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/pirate-*.whl
            dist/pirate-*.img
            dist/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}